---
# Completely disable problematic engines
engines:
  markdownlint:
    enabled: false
  shellcheck:
    enabled: false
  # Disable all other engines that might cause issues
  checkstyle:
    enabled: false
  pmd:
    enabled: false

# Aggressive path exclusions
exclude_paths:
  # Exclude all problematic directories
  - ".context/**/*"
  - ".github/**/*"
  - "ansible/**/*"
  - "**/*.md"
  - "**/*.yml"
  - "**/*.yaml"
  - "**/.*"
  - "**/node_modules/**/*"
  - "**/.git/**/*"
  - "**/dist/**/*"
  - "**/build/**/*"
  - "**/coverage/**/*"
  - "**/*.sarif"
  - "**/*.xml"
  - "**/*.log"
  - "**/*.tmp"
  # Exclude files with encoding issues
  - "**/CHANGELOG*"
  - "**/README*"
  - "**/*readme*"
  - "**/docs/**/*"
  - "**/storage/**/*"
  - "**/logs/**/*"

file_exclusions:
  extensions:
    - ".md"
    - ".yml"
    - ".yaml"
    - ".sarif"
    - ".xml"
    - ".log"
    - ".tmp"
